-- Inventario de herramientas tecnológicas, sin almacenar credenciales.
begin;

create table if not exists public.cuentas_tecnologia (
  id bigint generated by default as identity primary key,
  herramienta text not null check (btrim(herramienta) <> ''),
  plan text not null check (btrim(plan) <> ''),
  dia_renovacion smallint not null check (dia_renovacion between 1 and 31),
  costo numeric(12, 2) check (costo is null or costo >= 0),
  moneda text not null default 'COP',
  creado_por uuid not null default auth.uid() references auth.users (id),
  creado_en timestamptz not null default now()
);

alter table public.cuentas_tecnologia enable row level security;

grant select, insert, update, delete on public.cuentas_tecnologia to authenticated;
grant usage, select on sequence public.cuentas_tecnologia_id_seq to authenticated;

drop policy if exists "cuentas tecnologia: lectura interna" on public.cuentas_tecnologia;
create policy "cuentas tecnologia: lectura interna"
  on public.cuentas_tecnologia
  for select to authenticated
  using (public.tiene_rol(array['admin', 'comercial', 'comunicacion', 'auditor']));

drop policy if exists "cuentas tecnologia: administracion admin" on public.cuentas_tecnologia;
create policy "cuentas tecnologia: administracion admin"
  on public.cuentas_tecnologia
  for all to authenticated
  using (public.tiene_rol(array['admin']))
  with check (public.tiene_rol(array['admin']));

notify pgrst, 'reload schema';
commit;
